### ISSUE TITLE
0.8.1 version does not include latest version

### ISSUE THREAD

**Issue by aneveu** [wiremock/wiremock-graphql-extension#20]
### Proposal

Hey 👋 

I've installed the `0.8.1` version but it looks like it's the `0.7.0` version that is packaged in it. (It's missing `GraphqlBodyMatcher.parameters` + `GraphqlBodyMatcher.withRequest` and `GraphqlBodyMatcher.withRequestJson` are not marked as deprecated). Maybe a variable in GitHub action's release task pointing to this version in particular?

### Reproduction steps

Install the latest version and try the sample code in the README.md

**Comment by nilwurtz** [comment]
I apologize for the inconvenience.

0.8.1 is the version as of [e5d028face4275ff006c4f559c82931a64cce8c0](https://github.com/wiremock/wiremock-graphql-extension/commit/e5d028face4275ff006c4f559c82931a64cce8c0).
Once 0.8.2 is released, the HEAD source will be released.

**Comment by aneveu** [comment]
Thank you!
