### ISSUE TITLE
Add a Testcontainers demo/example

### ISSUE THREAD

**Issue by oleg-nenashev** [wiremock/wiremock-graphql-extension#8]
### Summary

I would like to add an example that demonstrates use of the extension with Testcontainers modules for WireMock, in particular Java, Python and Golang. As a part of it, it might even make sense to add some APIs to the SDKs to make the use of the extensions easier. To be seen

### References

- https://wiremock.org/docs/solutions/testcontainers/

**Comment by nilwurtz** [comment]
I think it would be good to work on this after wiremock-testcontainers-java has officially supported for WireMock Version 3. However, I do plan on using it for Integration Tests!

**Comment by oleg-nenashev** [comment]
Hi @nilwurtz. It is officially supported now, kinda. At least it is fully compatible

**Comment by nilwurtz** [comment]
The testcontainers-kotlin example has now been released 🥳
